---
title: "Employee Attrition Review"
author: "Lani Lewis"
date: "2023-03-30"
output: html_document
runtime: shiny
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include = FALSE}
# LIBRARIES ####
library(ggplot2)
library(tidyverse)
library(plotly)
library(shiny)
#library(RCurl)
#library(aws.s3)
#library(gridExtra)
library(class)
library(caret)
library(e1071)
#library(kknn)
#install.packages('RColorBrewer')
library(RColorBrewer)
```

```{r include = FALSE}
# Import Dataset
# getwd()
#attrition <- read.csv(file = "CaseStudy2-data.csv",header = T)
attrition <- read.csv("CaseStudy2-data.csv", header = T)


# REPLACE attrition with new values ####
attrition$Attrition <- gsub("No", "Stayed", attrition$Attrition)
attrition$Attrition <- gsub("Yes", "Left", attrition$Attrition)
#attrition$Attrition

# FORCE COLORS FOR Attrition ####
colors <- c("Stayed" = "green", "Left" = "red")
```


```{r include = FALSE}
# Configure KNN ####
train <- attrition 

set.seed(123)

## Change to FActors ####
train$Attrition = as.factor(train$Attrition)
train$Gender = as.factor(train$Gender)


## Split Data 70-30 | KNN ####
index <- createDataPartition(train$MonthlyIncome, p = 0.7, list = FALSE)
train_knn <- attrition[index, ]
test_knn <- attrition[-index, ]

```

```{r echo = FALSE}
# GUI SETUP ####
ui <- fluidPage(

  # App title ----
  titlePanel("Attrition: Describes if an employee has left a company."),
    
    # Tabset panel with two tabs ----
    tabsetPanel(
    tabPanel("Attrition Scatter Plot", subtitle = "High Level View of Employee Attrition",
             
        # Sidebar layout with input and output definitions #### ----
        sidebarLayout(
          
          # Sidebar panel for inputs ----
          # Main Panel
          sidebarPanel(
          # Input: Slider for the number of bins ----
            # Column
                  selectInput("xaxis", 
                        "Select x Axis Value", 
                        choices = c("Department" = "Department",
                                    "Gender" = "Gender",
                                    "DistanceFromHome" = "DistanceFromHome",
                                    "HourlyRate" = "HourlyRate",
                                    "MonthlyIncome" = "MonthlyIncome",
                                    "JobLevel" = "JobLevel",
                                    "YearsAtCompany" = "YearsAtCompany",
                                    "YearsSinceLastPromotion" = "YearsSinceLastPromotion",
                                    "StandardHours" = "StandardHours",
                                    "JobRole" = "JobRole"),
                        selected = "Department"),
                   selectInput("yaxis", 
                        "Select y Axis Value", 
                        choices = c("JobRole" = "JobRole",
                                    "EnvironmentSatisfaction" = "EnvironmentSatisfaction",
                                    "YearsAtCompany" = "YearsAtCompany",
                                    "PercentSalaryHike" = "PercentSalaryHike",
                                    "Education" = "Education",
                                    "JobInvolvement" = "JobInvolvement",
                                    "JobSatisfaction" = "JobSatisfaction",
                                    "PerformanceRating" = "PerformanceRating",
                                    "OverTime" = "OverTime",
                                    "Department" = "Department"),
                        selected = "JobRole"),
            
          ),
          
       # Main panel for displaying outputs ----
          mainPanel(
            
            # Output dataframe is distPlot
            plotOutput(outputId = "distPlot")
        ) 
       ) # sidebar layout
    ), # end of Plot tabPanel
    
  tabPanel("KNN Classifications", subtitle = "This tab is used to perform basic KNN Classification", 
             p("This classification is only looking at integers (Binomial) values."),
        # Sidebar with input options
  sidebarLayout(
    sidebarPanel(
      sliderInput("bestk", "Select the Best K:", min = 1, max = 10, value = 5),
      selectInput("pred1", "Select the First Classifying Variable:", choices = c("Age" = "Age",
                                    "DistanceFromHome" = "DistanceFromHome",
                                    "JobLevel" = "JobLevel"),
                        selected = "Age"),
      selectInput("pred2", "Select the Second Classifying Variable:", choices = c("MonthlyIncome" = "MonthlyIncome",  
                                    "HourlyRate" = "HourlyRate",
                                    "JobSatisfaction" = "JobSatisfaction"),
                        selected = "MonthlyIncome"),
      selectInput("class", "Select the Predictive Variable:", choices = c("Attrition" = "Attrition",
                                    "Gender" = "Gender"),
                        selected = "Attrition")
    ),

    # Main panel
    mainPanel(
      plotOutput("knnreview")
    )
       ) # sidebar layout 
    ), # end of KNN Review tabPanel
  
  tabPanel("Naive Bayes (NB) Predictions",  subtitle = "This tab is used to perform basic NB predictions", 
            
        # Sidebar layout with input and output definitions ----
        sidebarLayout(
          
          # Sidebar panel for inputs ----
          # Main Panel
          sidebarPanel(
          
                  #Input: Slider for the number of bins ----
                  selectInput("classifier1", 
                        "Select Predictor 1", 
                        choices = c("Age" = "Age",
                                    "DistanceFromHome" = "DistanceFromHome",
                                    "JobLevel" = "JobLevel"),
                        selected = "Age"),
          
                   selectInput("classifier2", 
                        "Select Predictor 2", 
                        choices = c("JobRole" = "JobRole",
                                    "HourlyRate" = "HourlyRate",
                                    "JobSatisfaction" = "JobSatisfaction"),
                        selected = "JobRole"),

                   selectInput("predictor", 
                        "Select Classifier (class)", 
                        choices = c("Attrition" = "Attrition",
                                    "MonthlyIncome" = "MonthlyIncome"),
                        selected = "MonthlyIncome"),
            
          ),
          
       # Main panel for displaying outputs ----
          mainPanel(
            
            # Output dataframe is distPlot
            plotOutput(outputId = "nbreview")
        ) 
       ) # sidebar layout 
    ), # end of KNN Review tabPanel
     
  ) # end of tabsetPanel       
             
) # fluidpage
```



```{r  echo = FALSE}
# OUTPUT SETUP ####
server <- function(input, output) {

  output$distPlot <- renderPlot({
    # SELECT XAXIS VALUES FIRST #####
    
    attrition %>% ggplot(aes(y = y, x = x, color = Attrition)) +
        geom_point(position = "jitter") +
        xlab(input$xaxis) +
        ylab(input$yaxis) +
        ggtitle(paste("This Report Compares ", input$xaxis, " and ", input$yaxis))
    
    if(input$xaxis == "Department"){
          x    <- train$Department
          
    }
 
    if(input$xaxis == "Gender"){
           x    <- train$Gender
       
    }    
    
    if(input$xaxis == "DistanceFromHome"){
          x    <- train$DistanceFromHome
        
    }    
    
    if(input$xaxis == "HourlyRate"){
          x    <- train$HourlyRate
          
    }    
    
    if(input$xaxis == "MonthlyIncome"){
          x    <- train$MonthlyIncome
          
    }
    
    if(input$xaxis == "JobLevel"){
          x    <- train$JobLevel
          
    }    
    
    if(input$xaxis == "YearsAtCompany"){
          x    <- train$YearsAtCompany
          
    }
    
    if(input$xaxis == "YearsSinceLastPromotion"){
          x    <- train$YearsSinceLastPromotion
          
    }
    
    if(input$xaxis == "StandardHours"){
          x    <- train$StandardHours
         
    }    
    if(input$xaxis == "JobRole"){
          x    <- train$JobRole
   
    }
    
    # SECOND SETUP YAXIS ####
          if(input$yaxis == "JobRole") {
             y    <- train$JobRole
          }
          if(input$yaxis == "EnvironmentSatisfaction") {
             y    <- train$EnvironmentSatisfaction
          }
          if(input$yaxis == "YearsAtCompany") {
             y    <- train$YearsAtCompany
          }
          if(input$yaxis == "PercentSalaryHike") {
             y    <- train$PercentSalaryHike
          }
          if(input$yaxis == "Education") {
             y    <- train$Education
          }
          if(input$yaxis == "JobInvolvement") {
             y    <- train$JobInvolvement
          }
          if(input$yaxis == "JobSatisfaction") {
             y    <- train$JobSatisfaction
          }
          if(input$yaxis == "PerformanceRating") {
             y    <- train$PerformanceRating
          }
          if(input$yaxis == "OverTime") {
             y    <- train$OverTime
          } 
          if(input$yaxis == "Department") {
             y    <- train$Department
          }
          
        train %>% ggplot(aes(y = y, x = x, color = Attrition)) +
        geom_point(position = "jitter") +
        xlab(input$xaxis) +
        ylab(input$yaxis) +
        scale_color_manual(values = colors) + 
        ggtitle(paste("This Report Compares ", input$xaxis, " and ", input$yaxis))
        
  }) # displot
  
# -------------------------------------------------
  
  output$knnreview <- renderPlot({
    
       # Get selected variables
    pred1 <- input$pred1
    pred2 <- input$pred2
    class <- input$class

    # Perform KNN classification
    #knn <- knn(train[,c(classvar1, classvar2)], train[,predictvar], k = input$bestk)
    # Generate color palette
    num_classes <- length(unique(train[,class]))
    color_palette <- colorRampPalette(brewer.pal(num_classes, "Set1"))
    
    # Run kNN algorithm
    knn <- knn.cv(train[,c(pred1, pred2)], train[, class], k = input$bestk)
    
    # Create plot with custom color palette
    plot(train[,pred1], 
         train[,pred2], 
         col = color_palette(num_classes)[train[,class]],
         pch = 20, cex = 2, 
         legend = levels(train[,class]), 
         main = paste("k-NN Classification (k =", input$bestk, ")"),
         xlab = pred1, ylab = pred2, 
         xlim = range(train[,pred1]), ylim = range(train[,pred2]))
    
    # Add color key
    legend("topright", 
       legend = levels(train[,class]), 
       col = color_palette(num_classes),
       pch = 20, 
       title = "Class")    
    
  }) # knnReview
  
# -------------------------------------------------
  
  output$nbreview <- renderPlot({
    classifier1 <- input$classifier1
    classifier2 <- input$classifier2
    predictor <- input$predictor
    
    
    nb <- naiveBayes(train[[predictor]] ~ as.factor(paste(train[[classifier1]], train[[classifier2]], sep = ",")), 
                     data = train)
    
    
    nb_pred <- predict(nb, data.frame(classifier1 = train[[classifier1]], 
                                      classifier2 = train[[classifier2]]))
    
    
    df <- data.frame(classifier1 = train[[classifier1]], 
                     classifier2 = train[[classifier2]],
                     class = nb_pred)
    
    
    ggplot(df, aes(x = classifier1, fill = class)) +
      geom_bar(position = "dodge") +
      facet_wrap(~classifier2) +
      labs(x = NULL, y = NULL, fill = "Class") +
      theme_minimal() +
      scale_fill_manual(values = c("blue", "lightblue", "lightgreen"))
  })
} # Server  

shinyApp(ui, server) # Combines it all together

```
